options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/github.com/scroll2learn/hero-labs-1302:$SHORT_SHA
      - -f
      - Dockerfile
      - .

images:
  - gcr.io/$PROJECT_ID/github.com/scroll2learn/hero-labs-1302:$SHORT_SHA